services:
  soundhound-bot:
    image: ghcr.io/doomhound188/soundhound:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      lavalink:
        condition: service_healthy

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: unless-stopped
    environment:
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -fsS -H "Authorization: Bearer ${LAVALINK_PASSWORD}" http://localhost:2333/version',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
